# Generated by Django 2.1.1 on 2018-09-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20180927_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientstranslations',
            options={'verbose_name': 'IngredientsTranslation', 'verbose_name_plural': 'IngredientsTranslations'},
        ),
        migrations.AlterModelOptions(
            name='mainingredients',
            options={'verbose_name': 'MainIngredient', 'verbose_name_plural': 'MainIngredients'},
        ),
    ]
