# Generated by Django 2.1.1 on 2018-09-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20180927_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientstranslations',
            options={'verbose_name': 'Ingredients Translation', 'verbose_name_plural': 'Ingredients Translations'},
        ),
        migrations.AlterModelOptions(
            name='mainingredients',
            options={'verbose_name': 'Main Ingredient', 'verbose_name_plural': 'Main Ingredients'},
        ),
    ]
