# Generated by Django 2.1.1 on 2018-09-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20180927_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstranslations',
            name='language_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
