# Generated by Django 2.1.1 on 2018-09-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_ingredients_main_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
