# Generated by Django 2.0.3 on 2018-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20181014_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.RecipeType'),
        ),
        migrations.AlterUniqueTogether(
            name='recipetype',
            unique_together={('name',)},
        ),
    ]
